version = 0.1

[default.deploy.parameters]
stack_name = "s3-test-stack"
resolve_s3 = true
s3_prefix = "s3-test-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
