AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Runtime: java21
    Environment:
      Variables:
        BUCKET_NAME: kev-garbage-bin

Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.example.lambda.CreateUserHandler::handleRequest
      Policies:
        - S3ReadPolicy:
            BucketName: kev-garbage-bin
        - S3WritePolicy:
            BucketName: kev-garbage-bin
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /users
            Method: post

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.example.lambda.GetUserHandler::handleRequest
      Policies:
        - S3ReadPolicy:
            BucketName: kev-garbage-bin
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: get

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.example.lambda.DeleteUserHandler::handleRequest
      Policies:
        - S3ReadPolicy:
            BucketName: kev-garbage-bin
        - S3WritePolicy:
            BucketName: kev-garbage-bin
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: delete

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"